# ===================================================================
# MicroMonitor Sample Spring Cloud Config.
# ===================================================================
spring:
    application:
        name: micromonitor

# Property used on app startup to check the config server status
configserver:
    name: MicroMonitor config server
    status: Connected to the MicroMonitor config server!

# Default JWT secret token (to be changed in production!)
micromonitor:
    security:
        authentication:
            jwt:
                base64-secret: 4W9YQ2ZjCPDBESsl0FdwijQ2Ifvquhmhm1hU+nCXuoBaxTs3bxcXiatnpJjAy8226K6xEWJoBlk9tYgH19d/Bg==
                secret: microservice_secret_key
                token-validity-in-seconds: 86400
logging:
    config: classpath:logback-spring.xml
    path: logs
    file: ${logging.path}/server.log


