os:
  - linux
services:
  - docker
install:
  - docker build -t micromonitor/micromonitor:travis .
  - docker images
  - docker run --name micromonitor -p 8761:8761 -d -t micromonitor/micromonitor:travis
script:
  - sleep 45
  - docker ps
  - docker logs micromonitor
  - curl -v http://localhost:8761
