spring:
    application:
        name: MicroMonitor
    mvc:
        favicon:
            enabled: false
    security:
        user:
            name: admin
            password: admin
            roles: USER,ADMIN
    thymeleaf:
        mode: HTML

server:
    port: 8761

logging:
    config: classpath:logback-spring.xml

ribbon:
    eureka:
        enabled: true

zuul:
    prefix: /services/ #slash before and after
    strip-prefix: true

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile"]
    endpoint:
        health:
            show-details: when_authorized
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true

eureka:
    instance:
        appname: micromonitor
        instanceId: micromonitor:${spring.application.instance-id:${random.value}}
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.endpoints.web.base-path}/info
        health-check-url-path: ${management.endpoints.web.base-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}
            version: ${info.project.version}
    client:
        enabled: true
        fetch-registry: false
        register-with-eureka: false
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
        service-url:
            defaultZone: http://admin:${spring.security.user.password:admin}@localhost:${server.port}
    server:
        # see discussion about enable-self-preservation:
        # https://github.com/micromonitor/generator-micromonitor/issues/3654
        enable-self-preservation: false
        peer-node-read-timeout-ms: 1000
    dashboard:
        path: /registry
    datacenter: MicroMonitor-DataCenter
    environment: MicroMonitor-Environment

microservice:
    swagger:
        default-include-pattern: /(api|config)/.*
        title: MicroMonitor API
        description: MicroService API documentation
        version: ${info.project.version}
