version: '2'
services:
    mincromonitor-app:
        image: micromonitor
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${micromonitor.registry.password}@localhost:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${micromonitor.registry.password}@micromonitor:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://micromonitor-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=micro
            - MICROMONITOR_SLEEP=30 # gives time for the NgMcmonitor Registry to boot before the application
    micro-mongodb:
        extends:
            file: micromonitor.yml
            service: micromonitor-mongodb
    micromonitor:
        extends:
            file: micromonitor.yml
            service: micromonitor
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
