version: '2'
services:
    micromonitor:
        image: micromonitor/micromonitor:v4.0.6
        volumes:
            - ./central-server-config:/central-config
        # When run with the "dev" Spring profile, the MicroMonitor will
        # read the config from the local filesystem (central-server-config directory)
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_SECURITY_USER_PASSWORD=admin
            - MICROMONITOR_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
            # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
            # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://git.cardev.de/ccct/carsync-monitoring
            # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
        ports:
            - 8761:8761
